{% set name = "globalwarmingpotentials" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/globalwarmingpotentials-{{ version }}.tar.gz
  sha256: c0d98d6fe7fb7d21bc2c17d7b41dfdf5a08b3a80778943e1f0d2f7f29372038b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - globalwarmingpotentials
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/openclimatedata/globalwarmingpotentials
  summary: Global warming potentials of greenhouse gases from various IPCC reports
  license: CC0-1.0
  license_file: LICENSE
  dev_url: https://github.com/openclimatedata/globalwarmingpotentials

extra:
  recipe-maintainers:
    - mikapfl
