{% set name = "globalwarmingpotentials" %}
{% set version = "0.13.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/globalwarmingpotentials-{{ version }}.tar.gz
  sha256: b4922859df23174ec149b752f104324dcd708058ded73ac42e657c4255360e1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - uv-build
  run:
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - globalwarmingpotentials
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/openclimatedata/globalwarmingpotentials
  summary: Global warming potentials of greenhouse gases from various IPCC reports
  license: CC0-1.0
  license_file: LICENSE.txt
  dev_url: https://github.com/openclimatedata/globalwarmingpotentials

extra:
  recipe-maintainers:
    - mikapfl
