{% set name = "globalwarmingpotentials" %}
{% set version = "0.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/globalwarmingpotentials-{{ version }}.tar.gz
  sha256: e81eb717ff81d894e43fcdbee1de7a6f2d83e3e6b63789fada8fb24861a2952a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas
    - python >=3.6

test:
  imports:
    - globalwarmingpotentials
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openclimatedata/globalwarmingpotentials
  summary: Global warming potentials of greenhouse gases from various IPCC reports
  license: CC0-1.0
  license_file: LICENSE
  dev_url: https://github.com/openclimatedata/globalwarmingpotentials

extra:
  recipe-maintainers:
    - mikapfl
